# Depression Detection from Video Features using BiLSTM with Attention (DAIC-WOZ Dataset)

This notebook implements a complete machine learning pipeline for detecting depression from video-derived features, utilizing the DAIC-WOZ dataset. The pipeline encompasses data loading, extensive preprocessing, feature engineering through windowing, data standardization, and training a deep learning model based on Bidirectional Long Short-Term Memory (BiLSTM) networks with an attention mechanism for both binary classification (depressed/not depressed) and regression (PHQ-8 score prediction). The model is thoroughly evaluated using standard classification and regression metrics.

**Key Steps Covered:**

1.  **Data Loading and Initial Exploration**: Loading raw OpenFace features and PHQ-8 labels, and examining the data structure.
2.  **Data Preprocessing**: Implementing functions to filter frames based on `confidence` and `success` scores, and selecting relevant features by dropping unnecessary columns.
3.  **Data Windowing**: Creating overlapping time windows from the preprocessed time-series data to capture temporal dependencies.
4.  **Metadata Generation and Data Splitting**: Preparing a metadata DataFrame that links participant information, labels, and window files, and splitting the data into training, validation, and test sets based on pre-defined participant splits.
5.  **Feature Scaling**: Standardizing features using `StandardScaler` fitted only on the training data to prevent data leakage.
6.  **PyTorch Dataset and DataLoader**: Implementing custom `EDAICDataset` and `DataLoader` classes for efficient batch processing of the windowed data in PyTorch.
7.  **Model Architecture**: Defining `DepressionNet`, a BiLSTM model with an attention pooling layer, followed by shared features and separate heads for binary classification and PHQ-8 regression.
8.  **Training and Validation**: Setting up loss functions (CrossEntropyLoss with class weights for classification and MSELoss for regression), an optimizer (AdamW), and implementing training and validation loops with early stopping based on F1-score.
9.  **Model Evaluation**: Evaluating the final model on the unseen test set using a comprehensive set of metrics including accuracy, precision, recall, F1-score, confusion matrix for classification, and MAE, RMSE, R2 for regression.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import os
from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive")

# Change this after checking your Drive structure
PROCESSED_DIR = BASE_DIR / "DAIC_WOZ_VIDEO_BRANCH" / "data" / "processed"
RAW_DATA = BASE_DIR / "edaic3.0" / "313" / "features"

print("Exists:", PROCESSED_DIR.exists())
print("Path:", PROCESSED_DIR)

Exists: True
Path: /content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/data/processed

In [ ]:
df = pd.read_csv(RAW_DATA/"313_OpenFace2.1.0_Pose_gaze_AUs.csv")

In [ ]:
df

,frame,timestamp,confidence,success,pose_Tx,pose_Ty,pose_Tz,pose_Rx,pose_Ry,pose_Rz,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0.000,0.98,1,15.3,13.2,546.1,0.285,-0.024,-0.031,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.033,0.98,1,15.2,12.9,544.4,0.304,-0.025,-0.031,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.066,0.98,1,15.3,12.8,543.5,0.317,-0.022,-0.035,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.099,0.98,1,15.3,12.8,543.3,0.317,-0.022,-0.035,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.132,0.98,1,15.3,12.8,543.3,0.317,-0.022,-0.035,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22843,22844,753.646,0.98,1,52.2,34.6,551.2,0.352,0.098,0.090,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
22844,22845,753.679,0.98,1,52.5,34.8,550.1,0.356,0.097,0.089,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
22845,22846,753.712,0.98,1,52.7,35.1,550.5,0.354,0.091,0.090,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
22846,22847,753.745,0.98,1,53.1,35.2,550.0,0.354,0.085,0.088,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
22847,22848,753.778,0.98,1,53.7,35.6,550.5,0.363,0.082,0.086,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [ ]:
df.shape

(22848, 53)

In [ ]:
print(df.columns.tolist())

['frame', 'timestamp', 'confidence', 'success', 'pose_Tx', 'pose_Ty', 'pose_Tz', 'pose_Rx', 'pose_Ry', 'pose_Rz', 'gaze_0_x', 'gaze_0_y', 'gaze_0_z', 'gaze_1_x', 'gaze_1_y', 'gaze_1_z', 'gaze_angle_x', 'gaze_angle_y', 'AU01_r', 'AU02_r', 'AU04_r', 'AU05_r', 'AU06_r', 'AU07_r', 'AU09_r', 'AU10_r', 'AU12_r', 'AU14_r', 'AU15_r', 'AU17_r', 'AU20_r', 'AU23_r', 'AU25_r', 'AU26_r', 'AU45_r', 'AU01_c', 'AU02_c', 'AU04_c', 'AU05_c', 'AU06_c', 'AU07_c', 'AU09_c', 'AU10_c', 'AU12_c', 'AU14_c', 'AU15_c', 'AU17_c', 'AU20_c', 'AU23_c', 'AU25_c', 'AU26_c', 'AU28_c', 'AU45_c']

In [ ]:
def load_participant(path):

  df = pd.read_csv(path)
  print(f"load from path: {path} sucessful!")
  return df

def filter_frame(df):
  df_new = pd.DataFrame()
  df_filtered = df[
    (df["success"] == 1) &
    (df["confidence"] >= 0.8)
]
  original_frames = len(df)
  filtered_frames = len(df_filtered)

  print(f"Original: {original_frames}")
  print(f"Filtered: {filtered_frames}")
  print(f"Removed: {(original_frames-filtered_frames)/original_frames:.2%}")
  return df_filtered


def select_feature(df,drop_features):
  df=df.drop(columns=drop_features)
  return df

def save_processed_file(df,id):
  df.to_csv(PROCESSED_DIR / "new_processed" / f"{id}_nprocessed.csv", index=False)

In [ ]:
label_df = pd.read_csv(BASE_DIR / "edaic3.0" / "labels" / "Detailed_PHQ8_Labels.csv")
session_ids = np.array(label_df["Participant_ID"])
session_ids

array([300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
       353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
       366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378,
       379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391,
       392, 393, 395, 396, 397, 399, 400, 401, 402, 403, 404, 405, 406,
       407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419,
       420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432,
       433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445,
       446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458,
       459, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472,
       473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485,
       486, 487, 488, 489, 490, 491, 492, 601, 603, 608, 612, 617, 627,
       628, 632, 633, 641, 653, 654, 657, 660, 662, 667, 670, 673, 677,
       680, 684, 687, 692, 695, 697, 698, 702, 703, 707, 713])

In [ ]:
label_df.head()

,Participant_ID,PHQ_8NoInterest,PHQ_8Depressed,PHQ_8Sleep,PHQ_8Tired,PHQ_8Appetite,PHQ_8Failure,PHQ_8Concentrating,PHQ_8Moving,PHQ_8Total,PHQ8_Binary,PHQ8_MultiClass
0,300,0,0,1,0,1,0,0,0,2,0,No Depression
1,301,0,0,1,1,1,0,0,0,3,0,No Depression
2,302,1,1,0,1,0,1,0,0,4,0,No Depression
3,303,0,0,0,0,0,0,0,0,0,0,No Depression
4,304,0,1,1,2,2,0,0,0,6,0,No Depression

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np

# ---------------------------
# CONFIG
# ---------------------------

BASE_DIR = Path("/content/drive/MyDrive")

drop_features = [
    "frame",
    "timestamp",
    "confidence",
    "success"
]

# ---------------------------
# DRIVER
# ---------------------------

def preprocessing_driver_script(session_ids, drop_features):

    summary = []

    for participant_id in session_ids:

        try:

            print(f"\nProcessing Participant {participant_id}...")

            file_path = (
                BASE_DIR
                / "edaic3.0"
                / str(participant_id)
                / "features"
                / f"{participant_id}_OpenFace2.1.0_Pose_gaze_AUs.csv"
            )

            # Load
            df = load_participant(file_path)

            original_frames = len(df)

            # Filter
            df_filtered = filter_frame(df)

            filtered_frames = len(df_filtered)

            removal_ratio = (
                (original_frames - filtered_frames)
                / original_frames
            )

            # Feature selection
            df_filtered = select_feature(
                df_filtered,
                drop_features
            )

            # Save
            save_processed_file(
                df_filtered,
                participant_id
            )

            # Summary row
            summary.append({
                "participant_id": participant_id,
                "original_frames": original_frames,
                "filtered_frames": filtered_frames,
                "removal_ratio": removal_ratio,
                "num_features": df_filtered.shape[1]
            })

            print(
                f"Saved | Frames: "
                f"{original_frames} -> {filtered_frames}"
            )

        except Exception as e:

            print(
                f"Error processing "
                f"{participant_id}: {e}"
            )

    summary_df = pd.DataFrame(summary)

    summary_df.to_csv(
        PROCESSED_DIR
        / "new_processed"
        / "preprocessing_summary.csv",
        index=False
    )

    return summary_df

In [ ]:
label_df = pd.read_csv(
    BASE_DIR
    / "edaic3.0"
    / "labels"
    / "Detailed_PHQ8_Labels.csv"
)

session_ids = label_df["Participant_ID"].tolist()

summary_df = preprocessing_driver_script(
    session_ids,   # test first
    drop_features
)

Processing Participant 300...
load from path: /content/drive/MyDrive/edaic3.0/300/features/300_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 19458
Filtered: 19378
Removed: 0.41%
Saved | Frames: 19458 -> 19378

Processing Participant 301...
load from path: /content/drive/MyDrive/edaic3.0/301/features/301_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24721
Filtered: 24618
Removed: 0.42%
Saved | Frames: 24721 -> 24618

Processing Participant 302...
load from path: /content/drive/MyDrive/edaic3.0/302/features/302_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 22766
Filtered: 22130
Removed: 2.79%
Saved | Frames: 22766 -> 22130

Processing Participant 303...
load from path: /content/drive/MyDrive/edaic3.0/303/features/303_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 29565
Filtered: 29400
Removed: 0.56%
Saved | Frames: 29565 -> 29400

Processing Participant 304...
load from path: /content/drive/MyDrive/edaic3.0/304/features/304_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23780
Filtered: 23368
Removed: 1.73%
Saved | Frames: 23780 -> 23368

Processing Participant 305...
load from path: /content/drive/MyDrive/edaic3.0/305/features/305_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 51122
Filtered: 50947
Removed: 0.34%
Saved | Frames: 51122 -> 50947

Processing Participant 306...
load from path: /content/drive/MyDrive/edaic3.0/306/features/306_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25744
Filtered: 25625
Removed: 0.46%
Saved | Frames: 25744 -> 25625

Processing Participant 307...
load from path: /content/drive/MyDrive/edaic3.0/307/features/307_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 37167
Filtered: 36844
Removed: 0.87%
Saved | Frames: 37167 -> 36844

Processing Participant 308...
load from path: /content/drive/MyDrive/edaic3.0/308/features/308_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26031
Filtered: 25243
Removed: 3.03%
Saved | Frames: 26031 -> 25243

Processing Participant 309...
load from path: /content/drive/MyDrive/edaic3.0/309/features/309_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 21391
Filtered: 21179
Removed: 0.99%
Saved | Frames: 21391 -> 21179

Processing Participant 310...
load from path: /content/drive/MyDrive/edaic3.0/310/features/310_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25609
Filtered: 25268
Removed: 1.33%
Saved | Frames: 25609 -> 25268

Processing Participant 311...
load from path: /content/drive/MyDrive/edaic3.0/311/features/311_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23810
Filtered: 23529
Removed: 1.18%
Saved | Frames: 23810 -> 23529

Processing Participant 312...
load from path: /content/drive/MyDrive/edaic3.0/312/features/312_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23945
Filtered: 23802
Removed: 0.60%
Saved | Frames: 23945 -> 23802

Processing Participant 313...
load from path: /content/drive/MyDrive/edaic3.0/313/features/313_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 22848
Filtered: 22640
Removed: 0.91%
Saved | Frames: 22848 -> 22640

Processing Participant 314...
load from path: /content/drive/MyDrive/edaic3.0/314/features/314_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 46873
Filtered: 46641
Removed: 0.49%
Saved | Frames: 46873 -> 46641

Processing Participant 315...
load from path: /content/drive/MyDrive/edaic3.0/315/features/315_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 29561
Filtered: 29087
Removed: 1.60%
Saved | Frames: 29561 -> 29087

Processing Participant 316...
load from path: /content/drive/MyDrive/edaic3.0/316/features/316_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26337
Filtered: 26105
Removed: 0.88%
Saved | Frames: 26337 -> 26105

Processing Participant 317...
load from path: /content/drive/MyDrive/edaic3.0/317/features/317_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24395
Filtered: 24354
Removed: 0.17%
Saved | Frames: 24395 -> 24354

Processing Participant 318...
load from path: /content/drive/MyDrive/edaic3.0/318/features/318_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 17833
Filtered: 17679
Removed: 0.86%
Saved | Frames: 17833 -> 17679

Processing Participant 319...
load from path: /content/drive/MyDrive/edaic3.0/319/features/319_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 20603
Filtered: 20020
Removed: 2.83%
Saved | Frames: 20603 -> 20020

Processing Participant 320...
load from path: /content/drive/MyDrive/edaic3.0/320/features/320_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25480
Filtered: 25145
Removed: 1.31%
Saved | Frames: 25480 -> 25145

Processing Participant 321...
load from path: /content/drive/MyDrive/edaic3.0/321/features/321_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24658
Filtered: 24567
Removed: 0.37%
Saved | Frames: 24658 -> 24567

Processing Participant 322...
load from path: /content/drive/MyDrive/edaic3.0/322/features/322_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31412
Filtered: 31317
Removed: 0.30%
Saved | Frames: 31412 -> 31317

Processing Participant 323...
load from path: /content/drive/MyDrive/edaic3.0/323/features/323_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25110
Filtered: 24353
Removed: 3.01%
Saved | Frames: 25110 -> 24353

Processing Participant 324...
load from path: /content/drive/MyDrive/edaic3.0/324/features/324_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 21640
Filtered: 21385
Removed: 1.18%
Saved | Frames: 21640 -> 21385

Processing Participant 325...
load from path: /content/drive/MyDrive/edaic3.0/325/features/325_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26251
Filtered: 26211
Removed: 0.15%
Saved | Frames: 26251 -> 26211

Processing Participant 326...
load from path: /content/drive/MyDrive/edaic3.0/326/features/326_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 20982
Filtered: 20557
Removed: 2.03%
Saved | Frames: 20982 -> 20557

Processing Participant 327...
load from path: /content/drive/MyDrive/edaic3.0/327/features/327_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 20427
Filtered: 20276
Removed: 0.74%
Saved | Frames: 20427 -> 20276

Processing Participant 328...
load from path: /content/drive/MyDrive/edaic3.0/328/features/328_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31956
Filtered: 31768
Removed: 0.59%
Saved | Frames: 31956 -> 31768

Processing Participant 329...
load from path: /content/drive/MyDrive/edaic3.0/329/features/329_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 21192
Filtered: 20979
Removed: 1.01%
Saved | Frames: 21192 -> 20979

Processing Participant 330...
load from path: /content/drive/MyDrive/edaic3.0/330/features/330_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23146
Filtered: 22875
Removed: 1.17%
Saved | Frames: 23146 -> 22875

Processing Participant 331...
load from path: /content/drive/MyDrive/edaic3.0/331/features/331_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25524
Filtered: 25296
Removed: 0.89%
Saved | Frames: 25524 -> 25296

Processing Participant 332...
load from path: /content/drive/MyDrive/edaic3.0/332/features/332_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26228
Filtered: 26121
Removed: 0.41%
Saved | Frames: 26228 -> 26121

Processing Participant 333...
load from path: /content/drive/MyDrive/edaic3.0/333/features/333_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 29081
Filtered: 29041
Removed: 0.14%
Saved | Frames: 29081 -> 29041

Processing Participant 334...
load from path: /content/drive/MyDrive/edaic3.0/334/features/334_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 29400
Filtered: 29104
Removed: 1.01%
Saved | Frames: 29400 -> 29104

Processing Participant 335...
load from path: /content/drive/MyDrive/edaic3.0/335/features/335_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24902
Filtered: 24673
Removed: 0.92%
Saved | Frames: 24902 -> 24673

Processing Participant 336...
load from path: /content/drive/MyDrive/edaic3.0/336/features/336_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 28337
Filtered: 28019
Removed: 1.12%
Saved | Frames: 28337 -> 28019

Processing Participant 337...
load from path: /content/drive/MyDrive/edaic3.0/337/features/337_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 56137
Filtered: 56036
Removed: 0.18%
Saved | Frames: 56137 -> 56036

Processing Participant 338...
load from path: /content/drive/MyDrive/edaic3.0/338/features/338_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 17906
Filtered: 17323
Removed: 3.26%
Saved | Frames: 17906 -> 17323

Processing Participant 339...
load from path: /content/drive/MyDrive/edaic3.0/339/features/339_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 25892
Filtered: 25684
Removed: 0.80%
Saved | Frames: 25892 -> 25684

Processing Participant 340...
load from path: /content/drive/MyDrive/edaic3.0/340/features/340_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 17980
Filtered: 17865
Removed: 0.64%
Saved | Frames: 17980 -> 17865

Processing Participant 341...
load from path: /content/drive/MyDrive/edaic3.0/341/features/341_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26027
Filtered: 26024
Removed: 0.01%
Saved | Frames: 26027 -> 26024

Processing Participant 343...
load from path: /content/drive/MyDrive/edaic3.0/343/features/343_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 27819
Filtered: 26522
Removed: 4.66%
Saved | Frames: 27819 -> 26522

Processing Participant 344...
load from path: /content/drive/MyDrive/edaic3.0/344/features/344_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 32718
Filtered: 32469
Removed: 0.76%
Saved | Frames: 32718 -> 32469

Processing Participant 345...
load from path: /content/drive/MyDrive/edaic3.0/345/features/345_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23818
Filtered: 23658
Removed: 0.67%
Saved | Frames: 23818 -> 23658

Processing Participant 346...
load from path: /content/drive/MyDrive/edaic3.0/346/features/346_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 36656
Filtered: 36472
Removed: 0.50%
Saved | Frames: 36656 -> 36472

Processing Participant 347...
load from path: /content/drive/MyDrive/edaic3.0/347/features/347_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 18348
Filtered: 18005
Removed: 1.87%
Saved | Frames: 18348 -> 18005

Processing Participant 348...
load from path: /content/drive/MyDrive/edaic3.0/348/features/348_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 21584
Filtered: 21498
Removed: 0.40%
Saved | Frames: 21584 -> 21498

Processing Participant 349...
load from path: /content/drive/MyDrive/edaic3.0/349/features/349_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 36479
Filtered: 36075
Removed: 1.11%
Saved | Frames: 36479 -> 36075

Processing Participant 350...
load from path: /content/drive/MyDrive/edaic3.0/350/features/350_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26455
Filtered: 26254
Removed: 0.76%
Saved | Frames: 26455 -> 26254

Processing Participant 351...
load from path: /content/drive/MyDrive/edaic3.0/351/features/351_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23090
Filtered: 22936
Removed: 0.67%
Saved | Frames: 23090 -> 22936

Processing Participant 352...
load from path: /content/drive/MyDrive/edaic3.0/352/features/352_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 22808
Filtered: 22776
Removed: 0.14%
Saved | Frames: 22808 -> 22776

Processing Participant 353...
load from path: /content/drive/MyDrive/edaic3.0/353/features/353_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 23584
Filtered: 23468
Removed: 0.49%
Saved | Frames: 23584 -> 23468

Processing Participant 354...
load from path: /content/drive/MyDrive/edaic3.0/354/features/354_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 17306
Filtered: 17240
Removed: 0.38%
Saved | Frames: 17306 -> 17240

Processing Participant 355...
load from path: /content/drive/MyDrive/edaic3.0/355/features/355_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 20242
Filtered: 19811
Removed: 2.13%
Saved | Frames: 20242 -> 19811

Processing Participant 356...
load from path: /content/drive/MyDrive/edaic3.0/356/features/356_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 28624
Filtered: 28256
Removed: 1.29%
Saved | Frames: 28624 -> 28256

Processing Participant 357...
load from path: /content/drive/MyDrive/edaic3.0/357/features/357_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 12447
Filtered: 11999
Removed: 3.60%
Saved | Frames: 12447 -> 11999

Processing Participant 358...
load from path: /content/drive/MyDrive/edaic3.0/358/features/358_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 19438
Filtered: 18403
Removed: 5.32%
Saved | Frames: 19438 -> 18403

Processing Participant 359...
load from path: /content/drive/MyDrive/edaic3.0/359/features/359_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31012
Filtered: 30123
Removed: 2.87%
Saved | Frames: 31012 -> 30123

Processing Participant 360...
load from path: /content/drive/MyDrive/edaic3.0/360/features/360_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 13214
Filtered: 12966
Removed: 1.88%
Saved | Frames: 13214 -> 12966

Processing Participant 361...
load from path: /content/drive/MyDrive/edaic3.0/361/features/361_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 19260
Filtered: 19031
Removed: 1.19%
Saved | Frames: 19260 -> 19031

Processing Participant 362...
load from path: /content/drive/MyDrive/edaic3.0/362/features/362_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 17710
Filtered: 17593
Removed: 0.66%
Saved | Frames: 17710 -> 17593

Processing Participant 363...
load from path: /content/drive/MyDrive/edaic3.0/363/features/363_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 36814
Filtered: 36768
Removed: 0.12%
Saved | Frames: 36814 -> 36768

Processing Participant 364...
load from path: /content/drive/MyDrive/edaic3.0/364/features/364_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 53447
Filtered: 53423
Removed: 0.04%
Saved | Frames: 53447 -> 53423

Processing Participant 365...
load from path: /content/drive/MyDrive/edaic3.0/365/features/365_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 41585
Filtered: 41365
Removed: 0.53%
Saved | Frames: 41585 -> 41365

Processing Participant 366...
load from path: /content/drive/MyDrive/edaic3.0/366/features/366_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 39381
Filtered: 38813
Removed: 1.44%
Saved | Frames: 39381 -> 38813

Processing Participant 367...
load from path: /content/drive/MyDrive/edaic3.0/367/features/367_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 49112
Filtered: 48560
Removed: 1.12%
Saved | Frames: 49112 -> 48560

Processing Participant 368...
load from path: /content/drive/MyDrive/edaic3.0/368/features/368_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 40645
Filtered: 39958
Removed: 1.69%
Saved | Frames: 40645 -> 39958

Processing Participant 369...
load from path: /content/drive/MyDrive/edaic3.0/369/features/369_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31236
Filtered: 30393
Removed: 2.70%
Saved | Frames: 31236 -> 30393

Processing Participant 370...
load from path: /content/drive/MyDrive/edaic3.0/370/features/370_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 36262
Filtered: 35696
Removed: 1.56%
Saved | Frames: 36262 -> 35696

Processing Participant 371...
load from path: /content/drive/MyDrive/edaic3.0/371/features/371_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 27356
Filtered: 26920
Removed: 1.59%
Saved | Frames: 27356 -> 26920

Processing Participant 372...
load from path: /content/drive/MyDrive/edaic3.0/372/features/372_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 45416
Filtered: 45083
Removed: 0.73%
Saved | Frames: 45416 -> 45083

Processing Participant 373...
load from path: /content/drive/MyDrive/edaic3.0/373/features/373_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 37951
Filtered: 37632
Removed: 0.84%
Saved | Frames: 37951 -> 37632

Processing Participant 374...
load from path: /content/drive/MyDrive/edaic3.0/374/features/374_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 38631
Filtered: 38487
Removed: 0.37%
Saved | Frames: 38631 -> 38487

Processing Participant 375...
load from path: /content/drive/MyDrive/edaic3.0/375/features/375_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 18636
Filtered: 17891
Removed: 4.00%
Saved | Frames: 18636 -> 17891

Processing Participant 376...
load from path: /content/drive/MyDrive/edaic3.0/376/features/376_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 30772
Filtered: 30570
Removed: 0.66%
Saved | Frames: 30772 -> 30570

Processing Participant 377...
load from path: /content/drive/MyDrive/edaic3.0/377/features/377_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 39851
Filtered: 39466
Removed: 0.97%
Saved | Frames: 39851 -> 39466

Processing Participant 378...
load from path: /content/drive/MyDrive/edaic3.0/378/features/378_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 26208
Filtered: 26041
Removed: 0.64%
Saved | Frames: 26208 -> 26041

Processing Participant 379...
load from path: /content/drive/MyDrive/edaic3.0/379/features/379_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 30065
Filtered: 29338
Removed: 2.42%
Saved | Frames: 30065 -> 29338

Processing Participant 380...
load from path: /content/drive/MyDrive/edaic3.0/380/features/380_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 58989
Filtered: 58501
Removed: 0.83%
Saved | Frames: 58989 -> 58501

Processing Participant 381...
load from path: /content/drive/MyDrive/edaic3.0/381/features/381_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 32681
Filtered: 32616
Removed: 0.20%
Saved | Frames: 32681 -> 32616

Processing Participant 382...
load from path: /content/drive/MyDrive/edaic3.0/382/features/382_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24728
Filtered: 24690
Removed: 0.15%
Saved | Frames: 24728 -> 24690

Processing Participant 383...
load from path: /content/drive/MyDrive/edaic3.0/383/features/383_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 41074
Filtered: 40856
Removed: 0.53%
Saved | Frames: 41074 -> 40856

Processing Participant 384...
load from path: /content/drive/MyDrive/edaic3.0/384/features/384_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31707
Filtered: 31192
Removed: 1.62%
Saved | Frames: 31707 -> 31192

Processing Participant 385...
load from path: /content/drive/MyDrive/edaic3.0/385/features/385_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 16091
Filtered: 15781
Removed: 1.93%
Saved | Frames: 16091 -> 15781

Processing Participant 386...
load from path: /content/drive/MyDrive/edaic3.0/386/features/386_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 31185
Filtered: 30956
Removed: 0.73%
Saved | Frames: 31185 -> 30956

Processing Participant 387...
load from path: /content/drive/MyDrive/edaic3.0/387/features/387_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 18084
Filtered: 17872
Removed: 1.17%
Saved | Frames: 18084 -> 17872

Processing Participant 388...
load from path: /content/drive/MyDrive/edaic3.0/388/features/388_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 24935
Filtered: 24271
Removed: 2.66%
Saved | Frames: 24935 -> 24271

Processing Participant 389...
load from path: /content/drive/MyDrive/edaic3.0/389/features/389_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 28597
Filtered: 27560
Removed: 3.63%
Saved | Frames: 28597 -> 27560

Processing Participant 390...
load from path: /content/drive/MyDrive/edaic3.0/390/features/390_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 40703
Filtered: 40329
Removed: 0.92%
Saved | Frames: 40703 -> 40329

Processing Participant 391...
load from path: /content/drive/MyDrive/edaic3.0/391/features/391_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 20405
Filtered: 20071
Removed: 1.64%
Saved | Frames: 20405 -> 20071

Processing Participant 392...
load from path: /content/drive/MyDrive/edaic3.0/392/features/392_OpenFace2.1.0_Pose_gaze_AUs.csv sucessful!
Original: 19671
Filtered: 19291
Removed: 1.93%
Saved | Frames: 19671 -> 19291

Processing Participant 393...

In [ ]:
summary_df.head()

,participant_id,original_frames,filtered_frames,removal_ratio,num_features
0,300,19458,19378,0.004111,49
1,301,24721,24618,0.004166,49
2,302,22766,22130,0.027936,49
3,303,29565,29400,0.005581,49
4,304,23780,23368,0.017325,49

In [ ]:
len(summary_df)

219

In [ ]:
FPS = 30

WINDOW_SIZE = 300   # 10 sec
STRIDE = 150        # 5 sec overlap

In [ ]:
import numpy as np

def generate_windows(df, window_size=300, stride=150):
    data = df.values
    windows = []
    start = 0
    while start + window_size <= len(data):
        window = data[start:start + window_size]
        windows.append(window)
        start += stride
    windows = np.array(windows)
    return windows

In [ ]:
df = pd.read_csv(
    PROCESSED_DIR /"new_processed"/ "300_nprocessed.csv"
)

windows = generate_windows(
    df,
    window_size=300,
    stride=150
)

print(windows.shape)

(128, 300, 49)

In [ ]:
print(windows[0].shape)

(300, 49)

In [ ]:
print(windows[0][:5])

[[ 6.95000e+01  3.77000e+01  5.76800e+02  2.21000e-01  3.60000e-02
  -6.80000e-02  1.53240e-02  2.98824e-01 -9.54185e-01 -1.87119e-01
   3.35262e-01 -9.23356e-01 -9.10000e-02  3.26000e-01  0.00000e+00
   0.00000e+00  5.90000e-01  5.30000e-01  0.00000e+00  0.00000e+00
   0.00000e+00  1.60000e-01  0.00000e+00  2.12000e+00  4.00000e-02
   5.10000e-01  0.00000e+00  1.40000e+00  1.50000e-01  6.40000e-01
   4.10000e-01  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
   1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 6.94000e+01  3.74000e+01  5.77500e+02  2.19000e-01  3.70000e-02
  -6.70000e-02  6.17400e-03  2.94520e-01 -9.55626e-01 -1.91460e-01
   3.36481e-01 -9.22021e-01 -9.80000e-02  3.24000e-01  0.00000e+00
   0.00000e+00  9.10000e-01  4.30000e-01  0.00000e+00  0.00000e+00
   0.00000e+00  1.90000e-01  0.00000e+00  2.08000e+00  1.00000e-02
   1.14000e+00  0.00000e+00  1.42000e+00  5.00000e-02  8.20000e-01
   4.60000e-01  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
   1.00000e+00  1.00000e+00  1.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 6.94000e+01  3.73000e+01  5.76700e+02  2.23000e-01  3.90000e-02
  -6.90000e-02  5.19200e-03  2.98043e-01 -9.54538e-01 -1.93294e-01
   3.40679e-01 -9.20095e-01 -1.00000e-01  3.28000e-01  0.00000e+00
   0.00000e+00  1.07000e+00  3.70000e-01  0.00000e+00  0.00000e+00
   0.00000e+00  2.10000e-01  0.00000e+00  2.12000e+00  2.00000e-02
   1.41000e+00  0.00000e+00  1.41000e+00  0.00000e+00  8.30000e-01
   4.70000e-01  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
   1.00000e+00  1.00000e+00  1.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 6.93000e+01  3.73000e+01  5.76500e+02  2.25000e-01  3.90000e-02
  -6.90000e-02  5.52300e-03  2.99662e-01 -9.54030e-01 -1.92734e-01
   3.42652e-01 -9.19480e-01 -1.00000e-01  3.30000e-01  0.00000e+00
   0.00000e+00  1.07000e+00  3.80000e-01  0.00000e+00  0.00000e+00
   0.00000e+00  1.60000e-01  0.00000e+00  2.11000e+00  7.00000e-02
   1.39000e+00  0.00000e+00  1.37000e+00  0.00000e+00  7.40000e-01
   3.70000e-01  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
   1.00000e+00  1.00000e+00  1.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 6.94000e+01  3.73000e+01  5.76600e+02  2.25000e-01  3.90000e-02
  -7.00000e-02  5.46100e-03  3.00506e-01 -9.53764e-01 -1.92661e-01
   3.42558e-01 -9.19530e-01 -1.00000e-01  3.31000e-01  0.00000e+00
   0.00000e+00  9.80000e-01  4.00000e-01  0.00000e+00  0.00000e+00
   0.00000e+00  3.70000e-01  0.00000e+00  1.90000e+00  1.90000e-01
   1.32000e+00  0.00000e+00  1.39000e+00  0.00000e+00  1.04000e+00
   3.60000e-01  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
   1.00000e+00  1.00000e+00  1.00000e+00  0.00000e+00  1.00000e+00
   0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]]

In [ ]:
WINDOWS_DIR = PROCESSED_DIR / "windows_processed"

In [ ]:
def save_windows(windows, participant_id):

    save_path = (
        WINDOWS_DIR /
        f"{participant_id}_windows.npy"
    )

    np.save(save_path, windows)

In [ ]:
for participant_id in session_ids:

    df = pd.read_csv(
        PROCESSED_DIR / "new_processed"/
        f"{participant_id}_nprocessed.csv"
    )

    windows = generate_windows(
        df,
        window_size=300,
        stride=150
    )

    save_windows(
        windows,
        participant_id
    )

    print(
        f"{participant_id}: "
        f"{windows.shape[0]} windows"
    )

300: 128 windows
301: 163 windows
302: 146 windows
303: 195 windows
304: 154 windows
305: 338 windows
306: 169 windows
307: 244 windows
308: 167 windows
309: 140 windows
310: 167 windows
311: 155 windows
312: 157 windows
313: 149 windows
314: 309 windows
315: 192 windows
316: 173 windows
317: 161 windows
318: 116 windows
319: 132 windows
320: 166 windows
321: 162 windows
322: 207 windows
323: 161 windows
324: 141 windows
325: 173 windows
326: 136 windows
327: 134 windows
328: 210 windows
329: 138 windows
330: 151 windows
331: 167 windows
332: 173 windows
333: 192 windows
334: 193 windows
335: 163 windows
336: 185 windows
337: 372 windows
338: 114 windows
339: 170 windows
340: 118 windows
341: 172 windows
343: 175 windows
344: 215 windows
345: 156 windows
346: 242 windows
347: 119 windows
348: 142 windows
349: 239 windows
350: 174 windows
351: 151 windows
352: 150 windows
353: 155 windows
354: 113 windows
355: 131 windows
356: 187 windows
357: 78 windows
358: 121 windows
359: 199 windows
360: 85 windows
361: 125 windows
362: 116 windows
363: 244 windows
364: 355 windows
365: 274 windows
366: 257 windows
367: 322 windows
368: 265 windows
369: 201 windows
370: 236 windows
371: 178 windows
372: 299 windows
373: 249 windows
374: 255 windows
375: 118 windows
376: 202 windows
377: 262 windows
378: 172 windows
379: 194 windows
380: 389 windows
381: 216 windows
382: 163 windows
383: 271 windows
384: 206 windows
385: 104 windows
386: 205 windows
387: 118 windows
388: 160 windows
389: 182 windows
390: 267 windows
391: 132 windows
392: 127 windows
393: 117 windows
395: 173 windows
396: 153 windows
397: 188 windows
399: 143 windows
400: 185 windows
401: 184 windows
402: 163 windows
403: 169 windows
404: 223 windows
405: 309 windows
406: 141 windows
407: 246 windows
408: 140 windows
409: 200 windows
410: 211 windows
411: 272 windows
412: 168 windows
413: 196 windows
414: 195 windows
415: 154 windows
416: 167 windows
417: 175 windows
418: 212 windows
419: 178 windows
420: 207 windows
421: 165 windows
422: 264 windows
423: 197 windows
424: 209 windows
425: 228 windows
426: 167 windows
427: 171 windows
428: 137 windows
429: 189 windows
430: 179 windows
431: 164 windows
432: 181 windows
433: 157 windows
434: 257 windows
435: 233 windows
436: 135 windows
437: 165 windows
438: 284 windows
439: 253 windows
440: 276 windows
441: 190 windows
442: 188 windows
443: 136 windows
444: 259 windows
445: 140 windows
446: 197 windows
447: 162 windows
448: 240 windows
449: 203 windows
450: 251 windows
451: 235 windows
452: 173 windows
453: 202 windows
454: 159 windows
455: 148 windows
456: 174 windows
457: 190 windows
458: 188 windows
459: 193 windows
461: 193 windows
462: 184 windows
463: 165 windows
464: 194 windows
465: 230 windows
466: 302 windows
467: 198 windows
468: 186 windows
469: 223 windows
470: 187 windows
471: 197 windows
472: 178 windows
473: 104 windows
474: 183 windows
475: 116 windows
476: 120 windows
477: 246 windows
478: 183 windows
479: 180 windows
480: 170 windows
481: 220 windows
482: 202 windows
483: 313 windows
484: 197 windows
485: 118 windows
486: 133 windows
487: 202 windows
488: 173 windows
489: 139 windows
490: 137 windows
491: 170 windows
492: 180 windows
601: 137 windows
603: 286 windows
608: 254 windows
612: 178 windows
617: 265 windows
627: 270 windows
628: 229 windows
632: 230 windows
633: 335 windows
641: 138 windows
653: 129 windows
654: 105 windows
657: 189 windows
660: 176 windows
662: 168 windows
667: 165 windows
670: 125 windows
673: 118 windows
677: 177 windows
680: 276 windows
684: 211 windows
687: 217 windows
692: 105 windows
695: 237 windows
697: 209 windows
698: 287 windows
702: 144 windows
703: 160 windows
707: 171 windows
713: 155 windows

In [ ]:
window_counts = []

for participant_id in session_ids:

    df = pd.read_csv(
        PROCESSED_DIR / "new_processed"/
        f"{participant_id}_nprocessed.csv"
    )

    windows = generate_windows(df)

    window_counts.append(
        windows.shape[0]
    )

print("Min:", min(window_counts))
print("Max:", max(window_counts))
print("Mean:", np.mean(window_counts))
print("Total:", len(window_counts))

Min: 78
Max: 389
Mean: 188.70319634703196
Total: 219

In [ ]:
CSV_PATH = "/content/drive/MyDrive/DAIC_WOZ_AUDIO_BRANCH/data/processed/wav2vec_5utt_segments_participant_split.csv"

df_split = pd.read_csv(CSV_PATH)
df_split = df_split.drop(columns=["sample_id", "sample_path", "num_samples", "duration_sec", "binary_label", "PHQ8_Score", "num_segments_merged"])
df_split.loc[438] = [438, "train"] # Corrected to assign both Participant_ID and split
df_unique = df_split.drop_duplicates(subset=["Participant_ID"], keep="first")
df_unique.head()

    Participant_ID  split
0              300  train
15             301   test
22             302    val
41             303   test
50             304  train

In [ ]:
# Find IDs in df1 that are NOT in df2
missing_in_df2 = set(label_df["Participant_ID"]) - set(df_unique["Participant_ID"])
print("Missing in df2:", missing_in_df2)

# Find IDs in df2 that are NOT in df1
missing_in_df1 = set(df_unique["Participant_ID"]) - set(label_df["Participant_ID"])
print("Missing in df1:", missing_in_df1)

Missing in df2: set()
Missing in df1: set()

In [ ]:
df_unique.shape

(219, 2)

In [ ]:
label_df = pd.merge(df_unique, label_df, on="Participant_ID", how="inner")

label_df.head()
label_df.shape

(219, 13)

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

def build_metadata(label_df, windows_dir):

    metadata = []

    for _, row in label_df.iterrows():

        participant_id = row["Participant_ID"]

        window_file = windows_dir / f"{participant_id}_windows.npy"

        if not window_file.exists():

            print(f"Missing windows for {participant_id}")
            continue

        windows = np.load(window_file)

        metadata.append({
            "participant_id": participant_id,
            "phq_score": row["PHQ_8Total"],
            "binary_label": row["PHQ8_Binary"],
            "num_windows": windows.shape[0],
            "window_file": str(window_file),
            "split":row["split"]
        })

    metadata_df = pd.DataFrame(metadata)

    return metadata_df

In [ ]:
metadata_df = build_metadata(
    label_df,
    WINDOWS_DIR
)

metadata_df.head()

,participant_id,phq_score,binary_label,num_windows,window_file,split
0,300,2,0,128,/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/d...,train
1,301,3,0,163,/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/d...,test
2,302,4,0,146,/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/d...,val
3,303,0,0,195,/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/d...,test
4,304,6,0,154,/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/d...,train

In [ ]:
metadata_df.to_csv(
    # BASE_DIR / "edaic3.0" / "metadata.csv",
    WINDOWS_DIR/"metadata.csv",
    index=False
)

In [ ]:
import pandas as pd
import numpy as np

metadata_df = pd.read_csv(
    WINDOWS_DIR/"metadata.csv"
)

In [ ]:
train_df = metadata_df[
    metadata_df["split"] == "train"
]

In [ ]:
train_df.shape

(131, 6)

In [ ]:
all_train_frames = []

for _, row in train_df.iterrows():

    windows = np.load(
        row["window_file"]
    )

    frames = windows.reshape(
        -1,
        windows.shape[-1]
    )

    all_train_frames.append(frames)

In [ ]:
all_train_frames = np.concatenate(
    all_train_frames,
    axis=0
)

print(all_train_frames.shape)

(7309500, 49)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(all_train_frames)

StandardScaler()

In [ ]:
import joblib

joblib.dump(
    scaler,
    PROCESSED_DIR/ "scaler.pkl"
)

['/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/data/processed/scaler.pkl']

In [ ]:
print(scaler.mean_.shape)
print(scaler.scale_.shape)

(49,)
(49,)

In [ ]:
sample = all_train_frames[:1000]

normalized = scaler.transform(sample)

print(normalized.mean(axis=0)[:5])
print(normalized.std(axis=0)[:5])

[ 0.31187817 -0.46481905  0.59503978 -0.28621905 -1.08553923]
[0.75634686 0.62155709 0.3345675  1.21278714 1.45562954]

In [ ]:
metadata_df["window_file"][0]

'/content/drive/MyDrive/DAIC_WOZ_VIDEO_BRANCH/data/processed/windows_processed/300_windows.npy'

In [ ]:
import torch

In [ ]:
from torch.utils.data import Dataset

class EDAICDataset(Dataset):

    def __init__(self, metadata_df):

        self.samples = []

        # iterate over metadata rows
        for _,row in metadata_df.iterrows():

        # load num_windows
          for win_idx in range(row["num_windows"]):

        # create one sample entry
            sample = {
                 "participant_id": row["participant_id"],
                  "window_idx": win_idx,
                  "phq_score": row["phq_score"],
                  "binary_label": row["binary_label"],
                  "window_file": row["window_file"]
            }
            self.samples.append(sample)

        # for each window

    def __len__(self):

        return len(self.samples)

    def __getitem__(self, idx):

        sample = self.samples[idx]

        # load npy
        windows = np.load(sample["window_file"])

        # extract window_idx
        window = windows[sample["window_idx"]]

        # return tensors
        binary_label = sample["binary_label"]
        phq_score = sample["phq_score"]
        participant_id = sample["participant_id"]
        window = torch.tensor(
            window,
            dtype=torch.float32
        )

        binary_label = torch.tensor(
            binary_label,
            dtype=torch.long
        )

        phq_score = torch.tensor(
            phq_score,
            dtype=torch.float32
        )
        return {
            "window": window,
            "binary_label": binary_label,
            "phq_score": phq_score,
            "participant_id": participant_id
        }

In [ ]:
dataset = EDAICDataset(metadata_df)

sample = dataset[0]

print(sample["window"].shape)
print(sample["binary_label"])
print(sample["phq_score"])
print(sample["participant_id"])

torch.Size([300, 49])
tensor(0)
tensor(2.)
300

In [ ]:
from torch.utils.data import DataLoader

train_df = metadata_df[
    metadata_df["split"] == "train"
]

val_df = metadata_df[
    metadata_df["split"] == "val"
]

test_df = metadata_df[
    metadata_df["split"] == "test"
]

In [ ]:
train_dataset = EDAICDataset(train_df)
val_dataset = EDAICDataset(val_df)
test_dataset = EDAICDataset(test_df)

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

In [ ]:
batch = next(iter(train_loader))

print(batch["window"].shape)
print(batch["binary_label"].shape)
print(batch["phq_score"].shape)

torch.Size([32, 300, 49])
torch.Size([32])
torch.Size([32])

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class AttentionPool(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()

        self.attention = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        """
        x: (B, T, H)
        """

        scores = self.attention(x).squeeze(-1)   # (B, T)

        weights = torch.softmax(scores, dim=1)   # (B, T)

        context = torch.sum(
            x * weights.unsqueeze(-1),
            dim=1
        )                                         # (B, H)

        return context, weights


class DepressionNet(nn.Module):

    def __init__(
        self,
        input_size=49,
        hidden_size=128,
        num_layers=2,
        dropout=0.3
    ):
        super().__init__()

        # BiLSTM
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout,
            bidirectional=True
        )

        lstm_output_dim = hidden_size * 2  # 256

        # Attention
        self.attention = AttentionPool(
            lstm_output_dim
        )

        # Shared representation
        self.shared = nn.Sequential(
            nn.Linear(lstm_output_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, 2)
        )

        # Regression head
        self.regressor = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        """
        x: (B,300,49)
        """

        lstm_out, _ = self.lstm(x)
        # (B,300,256)

        context, attention_weights = self.attention(
            lstm_out
        )
        # (B,256)

        shared_features = self.shared(
            context
        )
        # (B,128)

        class_logits = self.classifier(
            shared_features
        )
        # (B,2)

        phq_score = self.regressor(
            shared_features
        )
        # (B,1)

        return {
            "class_logits": class_logits,
            "phq_score": phq_score,
            "attention": attention_weights
        }

In [ ]:
model = DepressionNet()

x = torch.randn(
    32,
    300,
    49
)

outputs = model(x)

print(outputs["class_logits"].shape)
print(outputs["phq_score"].shape)
print(outputs["attention"].shape)

torch.Size([32, 2])
torch.Size([32, 1])
torch.Size([32, 300])

In [ ]:
train_df = metadata_df[
    metadata_df["split"] == "train"
]

print(train_df["binary_label"].value_counts())

binary_label
0    92
1    39
Name: count, dtype: int64

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import torch

labels = train_df["binary_label"].values

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(labels),
    y=labels
)

class_weights = torch.tensor(
    class_weights,
    dtype=torch.float32
)

print(class_weights)

tensor([0.7120, 1.6795])

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = DepressionNet().to(device)

In [ ]:
classification_criterion = nn.CrossEntropyLoss(
    weight=class_weights.to(device)
)

regression_criterion = nn.MSELoss()

In [ ]:
batch = next(iter(train_loader))

print(batch["window"].shape)
print(batch["binary_label"].shape)
print(batch["phq_score"].shape)

print(batch["window"].dtype)
print(batch["binary_label"].dtype)
print(batch["phq_score"].dtype)

torch.Size([32, 300, 49])
torch.Size([32])
torch.Size([32])
torch.float32
torch.int64
torch.float32

In [ ]:
def compute_loss(
    outputs,
    binary_labels,
    phq_scores,
    alpha=0.1
):

    classification_loss = classification_criterion(
        outputs["class_logits"],
        binary_labels
    )

    regression_loss = regression_criterion(
        outputs["phq_score"].squeeze(1),
        phq_scores
    )

    total_loss = (
        classification_loss
        + alpha * regression_loss
    )

    return (
        total_loss,
        classification_loss,
        regression_loss
    )

In [ ]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

model = DepressionNet().to(device)

In [ ]:
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

In [ ]:
def train_one_epoch(
    model,
    loader,
    optimizer,
    classification_criterion,
    regression_criterion,
    device,
    alpha=0.1
):

    model.train()

    total_loss = 0
    total_cls_loss = 0
    total_reg_loss = 0

    for batch in loader:

        windows = batch["window"].to(device)

        binary_labels = batch["binary_label"].to(device)

        phq_scores = batch["phq_score"].to(device)

        optimizer.zero_grad()

        outputs = model(windows)

        cls_loss = classification_criterion(
            outputs["class_logits"],
            binary_labels
        )

        reg_loss = regression_criterion(
            outputs["phq_score"].squeeze(1),
            phq_scores
        )

        loss = cls_loss + alpha * reg_loss

        loss.backward()

        optimizer.step()

        total_loss += loss.item()
        total_cls_loss += cls_loss.item()
        total_reg_loss += reg_loss.item()

    return (
        total_loss / len(loader),
        total_cls_loss / len(loader),
        total_reg_loss / len(loader)
    )

In [ ]:
from sklearn.metrics import (
    f1_score,
    accuracy_score,
    mean_squared_error
)

import numpy as np

In [ ]:
def validate(
    model,
    loader,
    classification_criterion,
    regression_criterion,
    device,
    alpha=0.1
):

    model.eval()

    total_loss = 0

    all_preds = []
    all_labels = []

    all_phq_preds = []
    all_phq_targets = []

    with torch.no_grad():

        for batch in loader:

            windows = batch["window"].to(device)

            binary_labels = batch["binary_label"].to(device)

            phq_scores = batch["phq_score"].to(device)

            outputs = model(windows)

            cls_loss = classification_criterion(
                outputs["class_logits"],
                binary_labels
            )

            reg_loss = regression_criterion(
                outputs["phq_score"].squeeze(1),
                phq_scores
            )

            loss = cls_loss + alpha * reg_loss

            total_loss += loss.item()

            preds = torch.argmax(
                outputs["class_logits"],
                dim=1
            )

            all_preds.extend(
                preds.cpu().numpy()
            )

            all_labels.extend(
                binary_labels.cpu().numpy()
            )

            all_phq_preds.extend(
                outputs["phq_score"]
                .squeeze(1)
                .cpu()
                .numpy()
            )

            all_phq_targets.extend(
                phq_scores.cpu().numpy()
            )

    f1 = f1_score(
        all_labels,
        all_preds
    )

    acc = accuracy_score(
        all_labels,
        all_preds
    )

    rmse = np.sqrt(
        mean_squared_error(
            all_phq_targets,
            all_phq_preds
        )
    )

    return (
        total_loss / len(loader),
        acc,
        f1,
        rmse
    )

In [ ]:
num_epochs = 30

best_f1 = 0

print("="*60)
print("Training Started")
print("="*60)
print(f"Device: {device}")
print(f"Train Samples: {len(train_dataset)}")
print(f"Val Samples: {len(val_dataset)}")
print(f"Batch Size: {train_loader.batch_size}")
print(f"Learning Rate: {optimizer.param_groups[0]['lr']}")
print("="*60)

for epoch in range(num_epochs):

    print(f"\n{'='*20} Epoch {epoch+1}/{num_epochs} {'='*20}")

    train_loss, train_cls, train_reg = train_one_epoch(
        model,
        train_loader,
        optimizer,
        classification_criterion,
        regression_criterion,
        device
    )

    val_loss, val_acc, val_f1, val_rmse = validate(
        model,
        val_loader,
        classification_criterion,
        regression_criterion,
        device
    )

    print(f"Train Total Loss : {train_loss:.4f}")
    print(f"Train Cls Loss   : {train_cls:.4f}")
    print(f"Train Reg Loss   : {train_reg:.4f}")

    print(f"Val Loss         : {val_loss:.4f}")
    print(f"Val Accuracy     : {val_acc:.4f}")
    print(f"Val F1 Score     : {val_f1:.4f}")
    print(f"Val RMSE         : {val_rmse:.4f}")

    if val_f1 > best_f1:

        best_f1 = val_f1

        torch.save(
            model.state_dict(),
            "best_model.pt"
        )

        print("\n🔥 New Best Model Saved!")
        print(f"Best F1: {best_f1:.4f}")

    else:

        print(
            f"\nNo Improvement | "
            f"Current Best F1 = {best_f1:.4f}"
        )

    print("-"*60)

============================================================
Training Started
============================================================
Device: cuda
Train Samples: 24365
Val Samples: 8197
Batch Size: 32
Learning Rate: 0.001
============================================================

==================== Epoch 1/30 ====================

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

In [ ]:
def evaluate_model(
    model,
    loader,
    device
):

    model.eval()

    all_cls_preds = []
    all_cls_labels = []

    all_phq_preds = []
    all_phq_labels = []

    with torch.no_grad():

        for batch in loader:

            windows = batch["window"].to(device)

            binary_labels = batch["binary_label"].to(device)

            phq_scores = batch["phq_score"].to(device)

            outputs = model(windows)

            cls_preds = torch.argmax(
                outputs["class_logits"],
                dim=1
            )

            phq_preds = outputs["phq_score"].squeeze(1)

            all_cls_preds.extend(
                cls_preds.cpu().numpy()
            )

            all_cls_labels.extend(
                binary_labels.cpu().numpy()
            )

            all_phq_preds.extend(
                phq_preds.cpu().numpy()
            )

            all_phq_labels.extend(
                phq_scores.cpu().numpy()
            )

    metrics = {

        "accuracy":
            accuracy_score(
                all_cls_labels,
                all_cls_preds
            ),

        "precision":
            precision_score(
                all_cls_labels,
                all_cls_preds,
                zero_division=0
            ),

        "recall":
            recall_score(
                all_cls_labels,
                all_cls_preds,
                zero_division=0
            ),

        "f1":
            f1_score(
                all_cls_labels,
                all_cls_preds,
                zero_division=0
            ),

        "confusion_matrix":
            confusion_matrix(
                all_cls_labels,
                all_cls_preds
            ),

        "mae":
            mean_absolute_error(
                all_phq_labels,
                all_phq_preds
            ),

        "rmse":
            np.sqrt(
                mean_squared_error(
                    all_phq_labels,
                    all_phq_preds
                )
            ),

        "r2":
            r2_score(
                all_phq_labels,
                all_phq_preds
            )
    }

    return metrics

In [ ]:
model.load_state_dict(
    torch.load(
        "best_model.pt",
        map_location=device
    )
)

model.to(device)

In [ ]:
test_metrics = evaluate_model(
    model,
    test_loader,
    device
)

In [ ]:
print("\n" + "="*60)
print("TEST RESULTS")
print("="*60)

print(
    f"Accuracy  : {test_metrics['accuracy']:.4f}"
)

print(
    f"Precision : {test_metrics['precision']:.4f}"
)

print(
    f"Recall    : {test_metrics['recall']:.4f}"
)

print(
    f"F1 Score  : {test_metrics['f1']:.4f}"
)

print(
    f"MAE       : {test_metrics['mae']:.4f}"
)

print(
    f"RMSE      : {test_metrics['rmse']:.4f}"
)

print(
    f"R2 Score  : {test_metrics['r2']:.4f}"
)

print("\nConfusion Matrix:")
print(
    test_metrics["confusion_matrix"]
)